### ISSUE TITLE
Autoscan - Chris

### ISSUE THREAD

**Issue by adamspanier** [DoctorEww/software-assurance#102]
Pick an automated code scanner and perform a scan on the code in question.

**Comment by khang1215** [comment]
Finished the scans, Do I need an separate folder for the scan images?  I uploaded all my images to the main folder, but couldn't make my own folder for the scanner I used.

**Comment by adamspanier** [comment]
There should be a directory already made for the auto scans. It's called AutomatedScan.

-------------------------------------
Adam M. Spanier
CyberCorps Cohort
University of Nebraska at Kearney
Discovery Hall 349
Kearney, NE 68849
________________________________

**Comment by khang1215** [comment]
Hmmm... I see a LGTM folder that you put your images in... I didn't know if
you wanted that for each individual scan program.

**Comment by adamspanier** [comment]
Ohhh! Yeah, go ahead and add your own directory! I'm a little slow on the uptake sometimes.

-------------------------------------
Adam M. Spanier
CyberCorps Cohort
University of Nebraska at Kearney
Discovery Hall 349
Kearney, NE 68849
________________________________

**Comment by khang1215** [comment]
lol... So... I was able to upload files and create a new file... but no
create directory option.

**Comment by adamspanier** [comment]
In GitHub, from the AutomatedScan directory: (1) create new file, (2) in fileName input box type: MyDirectoryName/readme.md, (3) navigate to MyDirectoryName, (4) upload files.

-------------------------------------
Adam M. Spanier
CyberCorps Cohort
University of Nebraska at Kearney
Discovery Hall 349
Kearney, NE 68849
________________________________

**Comment by khang1215** [comment]
You are amazing!
