### ISSUE TITLE
Manual CWE Review - Jensen

### ISSUE THREAD

**Issue by adamspanier** [DoctorEww/software-assurance#108]
* [CWE-347: Improper Verification of Cryptographic Signature](https://cwe.mitre.org/data/definitions/347.html)
* [CWE-326: Inadequate Encryption Strength (Code and Documentation)](https://cwe.mitre.org/data/definitions/326.html)

**Comment by jmiller859** [comment]
Added 326 justifications.

**Comment by jmiller859** [comment]
Added 347 justifications.
