### ISSUE TITLE
Generate 5 essential interactions with Use-Case Diagrams.

### ISSUE THREAD

**Issue by adamspanier** [DoctorEww/software-assurance#19]
DEADLINE: Will be decided in meeting on 9/21/2021

We'll each need to provide at least one possible essential interaction and use case for this assignment. Any overlap will need to be mitigated with more interactions and use-cases.

https://app.diagrams.net/

**Comment by adamspanier** [comment]
RESOURCE: https://unomaha.instructure.com/courses/49732/files/5283525?wrap=1

**Comment by khang1215** [comment]
Did you want us to come to the meeting tonight with 5 interactions each? or
is that the goal for tonight?

**Comment by adamspanier** [comment]
No need to come to the meeting with five cases! We'll set deadlines for each goal tonight in the meeting.

**Comment by khang1215** [comment]
okay, it sounded like Gandhi is expecting a use case to look at with the
meeting tomorrow... or did I read his email wrong?

**Comment by adamspanier** [comment]
You are absolutely right. We'll need at the VERY LEAST, five rough draft use-cases by tomorrow evening's meeting. I'd like to try to have more.
