### ISSUE TITLE
USE CASE - Exporting a vault

### ISSUE THREAD

**Issue by adamspanier** [DoctorEww/software-assurance#24]

**Comment by adamspanier** [comment]
When you have your Use Case diagrammed, upload it to the  usecase -> export_vault. The share_group_account will be managed by you!

**Comment by jmiller859** [comment]
Uploaded first revision, reviewing it at next meeting.

**Comment by jmiller859** [comment]
Reviewed with team and made final changes in commit 54eae2969ec661cdf02d98b365695d3cf2c92c1d
Made final captures and uploaded the saved dio file.

**Comment by adamspanier** [comment]
Diagram completed and approved.
